FROM python:3.8

WORKDIR /app

# Copy your application code and model file
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir scikit-learn==1.2.2 fastapi uvicorn[standard]

# Expose the port your FastAPI application will run on
EXPOSE 8000

# Command to run the FastAPI application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
